# Making an array from a data or another array

In [2]:
import numpy as np

In [4]:
a = np.arange(0, 222, 5) 
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [5]:
len(a)

45

In [6]:
arr1 = a[40:45]
arr1

array([200, 205, 210, 215, 220])

In [7]:
q = np.array([1, 2, 3, 4, 5,6,7,8])
w = np.array([9, 10, 11, 12, 13,14,15,16])


In [8]:
# verticly stack
e = np.vstack((q, w))
e

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [9]:
# horizontly stack
r = np.hstack((q, w))
r

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [11]:
# reshape
r1 = r.reshape(8, 2)
r1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])